steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/compare-446607/springboot-app', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/compare-446607/springboot-app']
images:
  - 'gcr.io/compare-446607/springboot-app'
